name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.GITHUB_REPOSITORY }}:latest
          cache-from: type=registry,ref=${{ vars.GITHUB_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ vars.GITHUB_REPOSITORY }}:buildcache,mode=max
